# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address_details', models.TextField(default=b'[{"location_address": "", "location_name": ""}]')),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], default='Silver', max_length=100)),
            ],
        ),
    ]
