# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.CharField(max_length=20)),
                ('order_details', models.TextField(default=b'{"submenu": "", "item_name": "", "item_cuisine": "", "special_instruction": "", "item_type": "", "item_id": "", "item_quantity": ""}')),
                ('order_time', models.DateTimeField(default=datetime.datetime(2017, 10, 2, 19, 5, 10, 902769, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default=b'"[]"', max_length=400),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='started_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application.Restaurant'),
        ),
    ]
