# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0004_auto_20171002_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='primary_contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 17, 8, 1, 866365, tzinfo=utc)),
        ),
    ]
