# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer_application', '0001_initial'),
        ('main_application', '0005_auto_20171004_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='current_customers',
            field=models.ManyToManyField(to='customer_application.Customer'),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 18, 49, 10, 80287, tzinfo=utc)),
        ),
    ]
