# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer_application', '0001_initial'),
        ('main_application', '0006_auto_20171110_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='for_customer',
            field=models.ManyToManyField(to='customer_application.Customer'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Kitchen', 'Kitchen'), ('Received', 'Received')], default='Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 10, 47, 37, 113218, tzinfo=utc)),
        ),
    ]
