# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0009_auto_20171115_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_count', models.CharField(default=0, max_length=20)),
                ('timings', models.TextField(default=b'[{"day_range": [], "timings": [{"from_time": "to_time"}]}]')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 19, 16, 16, 929129, tzinfo=utc)),
        ),
    ]
