# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0011_auto_20171202_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequests',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_application.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerrequests',
            name='requestTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 10, 35, 36, 83000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 10, 35, 36, 83000, tzinfo=utc)),
        ),
    ]
